import type { Metadata, Viewport } from "next";
import { SITE_DESCRIPTION, SITE_URL } from "@/lib/site/contact";
import { STUDIO_NAME } from "@/lib/site/studio";

/**
 * The pieces every page's metadata is assembled from.
 *
 * One builder rather than a metadata object per route, because the fields that matter most
 * here are the ones easiest to get subtly wrong twice: a canonical that points at the wrong
 * path, or an og:title that has drifted from the <title>. Passing a path and a title is the
 * only thing a route should have to decide.
 *
 * Both assets are plain files under `public/`, generated by scripts/generate-brand-images.mjs.
 */
export const SHARE_IMAGE_PATH = "/og.png";
export const LOGO_PATH = "/icon.png";

const SHARE_IMAGE = {
  url: SHARE_IMAGE_PATH,
  width: 1200,
  height: 630,
  alt: `${STUDIO_NAME} — ${SITE_DESCRIPTION}`,
};

/**
 * Join a root-relative path to the site origin.
 *
 * "/" is the special case: `${SITE_URL}/` and `SITE_URL` are the same page, and Next
 * resolves a "/" canonical down to the bare origin. Anything that states the homepage's URL
 * has to state it the same way the canonical does, or the sitemap and the breadcrumb are
 * nominating a URL the canonical disowns.
 */
export function absoluteUrl(path: string): string {
  return path === "/" ? SITE_URL : `${SITE_URL}${path}`;
}

export type PageSeo = {
  /** Omitted on the homepage, which takes the site name unmodified. */
  title?: string;
  description?: string;
  /** Path from the site root, leading slash included. */
  path: string;
};

export function pageMetadata({ title, description, path }: PageSeo): Metadata {
  const resolvedTitle = title ? `${title} — ${STUDIO_NAME}` : STUDIO_NAME;
  const resolvedDescription = description ?? SITE_DESCRIPTION;

  return {
    /**
     * The full string, not the bare page name. The layout cannot carry a title template
     * here — a page spreading its own metadata over the layout's replaces the title object
     * wholesale rather than filling in its `%s` — so each page states the whole title.
     */
    title: resolvedTitle,
    description: resolvedDescription,
    /**
     * Resolved against metadataBase. Every page states its own canonical: a static export
     * is reachable at more than one URL (with and without a trailing slash, and on whatever
     * preview domain it is deployed to first) and the canonical is what stops those being
     * indexed as separate pages.
     */
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      siteName: STUDIO_NAME,
      /**
       * Spelled out rather than inherited. og:title has no template mechanism, so a page
       * that sets only `title` would otherwise share with the bare word "Web".
       */
      title: resolvedTitle,
      description: resolvedDescription,
      url: absoluteUrl(path),
      locale: "en_IN",
      images: [SHARE_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title: resolvedTitle,
      description: resolvedDescription,
      images: [SHARE_IMAGE],
    },
  };
}

/**
 * Site-wide metadata that does not vary by page: what to crawl, and which icons to use.
 *
 * `max-image-preview: large` is the one directive here with a visible payoff — without it
 * Google restricts the thumbnail beside a result to a small square, which on a studio site
 * is the difference between a result that shows the work and one that does not.
 */
export const SITE_METADATA: Metadata = {
  metadataBase: new URL(SITE_URL),
  applicationName: STUDIO_NAME,
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-image-preview": "large",
      "max-snippet": -1,
      "max-video-preview": -1,
    },
  },
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "32x32" },
      { url: LOGO_PATH, type: "image/png", sizes: "512x512" },
    ],
    apple: "/apple-icon.png",
  },
};

/**
 * Painted into the browser chrome on mobile — the address bar on Android Chrome, the status
 * area of an installed page — so the frame around the site matches the page ground instead
 * of defaulting to the browser's own grey.
 *
 * One colour, not a light/dark pair: the site has a single light ground and no dark theme,
 * so offering a dark variant would tint the chrome for a page that never follows it.
 */
export const SITE_VIEWPORT: Viewport = {
  themeColor: "#faf9f7",
  colorScheme: "light",
};
